# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscribeEvent.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14subscribeEvent.proto\x12\x12\x65vent.subscription\"\xa9\x01\n\x05\x45vent\x12\x31\n\x04type\x18\x01 \x01(\x0e\x32#.event.subscription.Event.EventType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"J\n\tEventType\x12\t\n\x05SPORT\x10\x00\x12\t\n\x05MUSIC\x10\x01\x12\x0b\n\x07THEATER\x10\x02\x12\n\n\x06\x43INEMA\x10\x03\x12\x0e\n\nKEEP_ALIVE\x10\x04\"N\n\x13SubscriptionRequest\x12\x37\n\neventTypes\x18\x01 \x03(\x0e\x32#.event.subscription.Event.EventType2h\n\x11\x45ventNotification\x12S\n\tSubscribe\x12\'.event.subscription.SubscriptionRequest\x1a\x19.event.subscription.Event\"\x00\x30\x01\x42\'\n\x0bsr.grpc.genB\x16\x45ventSubscriptionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subscribeEvent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013sr.grpc.genB\026EventSubscriptionProtoP\001'
  _globals['_EVENT']._serialized_start=45
  _globals['_EVENT']._serialized_end=214
  _globals['_EVENT_EVENTTYPE']._serialized_start=140
  _globals['_EVENT_EVENTTYPE']._serialized_end=214
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=216
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=294
  _globals['_EVENTNOTIFICATION']._serialized_start=296
  _globals['_EVENTNOTIFICATION']._serialized_end=400
# @@protoc_insertion_point(module_scope)
